### ISSUE TITLE
Remove the dependency on GMP

### ISSUE THREAD

**Issue by BerryYoghurt** [elichai/ecc-secp256k1#1]
I am currently in the process of transpiling this library to C [see  [here](https://github.com/bitcoin-core/secp256k1/issues/1108)], but we believe that having GMP as a dependency might cause some complications. Until now, there hasn't been much difficulty; but because GMP is itself C ported to Rust, it might get more complicated later on to compile C which has been transpiled from Rust which itself uses C.

So could you please replace `rug` with some pure Rust big integer library? Thanks!

**Comment by elichai** [comment]
Done
